server:
  port: 3000

db:
  type: 'mysql'
  host: 'localhost'
  port: 3306
  username: 'root'
  password: ''
  database: 'books'

jwt:
  secret: 'topSecret'
  expiresIn: 3600

google:
  url: 'https://books.googleapis.com/books/v1/volumes'