server:
  port: 3000

db:
  type: 'mysql'
  host: ''
  port: 3306
  username: ''
  password: ''
  database: ''

jwt:
  secret: ''
  expiresIn: 3600

google:
  url: 'https://books.googleapis.com/books/v1/volumes'